# Generated by Django 6.0.3 on 2026-03-26 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0003_providermedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
