# Generated by Django 6.0.3 on 2026-03-26 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0004_provider_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='hero_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
