# Generated by Django 6.0.3 on 2026-03-27 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0005_provider_hero_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
