# Generated by Django 6.0.3 on 2026-04-10 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0007_provider_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderUnavailableDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unavailable_dates', to='providers.provider')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('provider', 'date')},
            },
        ),
    ]
