# Generated by Django 6.0.3 on 2026-03-26 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='consultation_type',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='offline', max_length=10),
        ),
    ]
