# Generated by Django 6.0.3 on 2026-04-10 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_booking_amount_booking_cancellation_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='hidden_for_provider',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='hidden_for_user',
            field=models.BooleanField(default=False),
        ),
    ]
