# Generated by Django 6.0.3 on 2026-03-22 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(max_length=150)),
                ('hospital_name', models.CharField(max_length=200)),
                ('provider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='providers.provider')),
            ],
        ),
    ]
